[phases.setup]
nixPkgs = ["python311", "gcc", "libstdcxx5"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run Project/frontend/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
